### ISSUE TITLE
Problem with "Edit connection window"

### ISSUE THREAD

**Issue by LANlito** [evsar3/sshfs-win-manager#127] opened 2021-12-21 11:38 UTC
It is impossible to select the disk name with the mouse in the edit connection window if the monitor has a resolution 1366x768
![image](https://user-images.githubusercontent.com/66920127/146923907-cc079666-6a3d-45d9-850d-9ce3f5446b34.png)

**Comment by evsar3** [comment] 2021-12-21 15:20
Duplicate of #113

**Closed by evsar3** 2021-12-21 15:20 UTC
