### ISSUE TITLE
Chocolately package

### ISSUE THREAD

**Issue by rklec** [evsar3/sshfs-win-manager#151] opened 2022-05-27 12:28 UTC
For [sshfs-win](https://github.com/winfsp/sshfs-win) a chocolatey package exists:

https://community.chocolatey.org/packages/sshfs

It would be great if a chocolately package would also exist for this project here.

**Comment by evsar3** [comment] 2022-07-14 18:12
Duplicate of #19

**Closed by evsar3** 2022-07-14 18:12 UTC
