### ISSUE TITLE
Stuck Connection no error

### ISSUE THREAD

**Issue by Ajgonbas** [evsar3/sshfs-win-manager#38] opened 2020-08-05 08:28 UTC
Good day.
I've been running SSHFS like this for over a month now, the connection at the top got stuck one day without message error, I had to create another one with the same parameters to be able to work, but I can't delete or edit the broken one.

Any ideas?

![image](https://user-images.githubusercontent.com/62634557/89389788-25ab9980-d706-11ea-86c1-5ce094be4147.png)

**Comment by evsar3** [comment] 2020-08-05 13:26
Duplicate of #9

**Closed by evsar3** 2020-08-05 13:26 UTC
