### ISSUE TITLE
[Feature Request] Option to reconnect connections on sshfs-win-manager startup

### ISSUE THREAD

**Issue by MilesTFox** [evsar3/sshfs-win-manager#51] opened 2020-10-01 16:41 UTC
I would like for there to be an option to set a connection to be re-connected when sshfs-win-manager starts.

This way, if I have sshfs-win-manager start with windows, the connections would be re-connected each time I log in to windows.

**Comment by evsar3** [comment] 2020-10-01 16:43
Duplicate of #50

**Closed by evsar3** 2020-10-01 16:43 UTC
