### ISSUE TITLE
I can't delete a connection

### ISSUE THREAD

**Issue by Telerin** [evsar3/sshfs-win-manager#29] opened 2020-06-25 20:19 UTC
I have the version 1.0.1. I connected a remote SFTP folder and was able to view the content and operate on it (S :). I minimized the application and when I opened it after an hour, the connection appeared trying to connect continuously. I have restarted Windows (windows 10), uninstalled and reinstalled sshfs-win-manager and it continues the same.
I have created another connection to the same folder (T :) and it works perfectly. The application does not allow to delete the first connection. How could I do it?

![sshfs101](https://user-images.githubusercontent.com/23387343/85791287-dbf88800-b731-11ea-87cc-42e9a26f2a5d.jpg)

**Comment by evsar3** [comment] 2020-06-25 20:28
Duplicate of #9

**Closed by evsar3** 2020-06-25 20:28 UTC
